title: Speedshop株式会社 - Ruby on Rails のパフォーマンスコンサルティング
email: nate.berkopec@speedshop.co
description: スピードショップ株式会社は、Ruby on Rails のパフォーマンスコンサルティング企業です。ツール、情報、トレーニングを通じて、Rails を使ったビジネスの収益を上げ、スケーリングコストを削減するためにすべてのスタック（フロントエンド、バックエンド、インフラ）を最適化します。高速なサイトは収益性の高いサイトであり、スピードは価値です。
baseurl: ""
url: "https://www.speedshop.co.jp"
permalink: /:year/:month/:day/:title.html
plugins:
  - jekyll-sitemap
markdown: kramdown
kramdown:
  auto_ids: true
encoding: utf-8
exclude:
   - _h2o
   - Procfile
   - wercker.yml
   - Gemfile
   - Gemfile.lock
